version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001" # ajuste se a porta do seu backend for diferente
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm install && npm start
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000" # ajuste se a porta for diferente
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm install && npm start
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
